//
// [Rebellions Inc.]("Rebellions") CONFIDENTIAL
// Unpublished Copyright (c) 2021-2026 [Rebellions Inc.], All Rights Reserved.
//
// NOTICE: All information contained herein is, and remains the property of Rebellions.
// The intellectual and technical concepts contained herein are proprietary to Rebellions
// and may be covered by Republic of Korea, U.S., and other countries' Patents, patents
// in process, and are protected by trade secret or copyright law.
//
// Dissemination of this information or reproduction of this material is strictly forbidden
// unless prior written permission is obtained from Rebellions. Access to the source code
// contained herein is hereby forbidden to anyone except current Rebellions employees, managers
// or contractors who have executed Confidentiality and Non-disclosure agreements explicitly
// covering such access.
//
// The copyright notice above does not evidence any actual or intended publication or disclosure
// of this source code, which includes information that is confidential and/or proprietary, and
// is a trade secret, of Rebellions.
//
// ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC PERFORMANCE, OR PUBLIC DISPLAY OF OR
// THROUGH USE OF THIS SOURCE CODE WITHOUT THE EXPRESS WRITTEN CONSENT OF REBELLIONS IS STRICTLY
// PROHIBITED, AND IN VIOLATION OF APPLICABLE LAWS AND INTERNATIONAL TREATIES. THE RECEIPT OR
// POSSESSION OF THIS SOURCE CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS
// TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE, USE, OR SELL ANYTHING
// THAT IT MAY DESCRIBE, IN WHOLE OR IN PART.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: rbln_services.proto

package rblnservicespb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RBLNServices_GetDeviceList_FullMethodName            = "/rblnservices.RBLNServices/getDeviceList"
	RBLNServices_GetServiceableDeviceList_FullMethodName = "/rblnservices.RBLNServices/getServiceableDeviceList"
	RBLNServices_ResetDevice_FullMethodName              = "/rblnservices.RBLNServices/resetDevice"
	RBLNServices_ResetAllDevice_FullMethodName           = "/rblnservices.RBLNServices/resetAllDevice"
	RBLNServices_GetVersion_FullMethodName               = "/rblnservices.RBLNServices/getVersion"
	RBLNServices_GetHWInfo_FullMethodName                = "/rblnservices.RBLNServices/getHWInfo"
	RBLNServices_GetMemoryInfo_FullMethodName            = "/rblnservices.RBLNServices/getMemoryInfo"
	RBLNServices_GetClockInfo_FullMethodName             = "/rblnservices.RBLNServices/getClockInfo"
	RBLNServices_GetEventInfo_FullMethodName             = "/rblnservices.RBLNServices/getEventInfo"
	RBLNServices_GetTotalInfo_FullMethodName             = "/rblnservices.RBLNServices/getTotalInfo"
	RBLNServices_GetUtilization_FullMethodName           = "/rblnservices.RBLNServices/getUtilization"
	RBLNServices_RblnListTopology_FullMethodName         = "/rblnservices.RBLNServices/RblnListTopology"
	RBLNServices_RblnListCoredumps_FullMethodName        = "/rblnservices.RBLNServices/RblnListCoredumps"
	RBLNServices_RblnGetConfig_FullMethodName            = "/rblnservices.RBLNServices/RblnGetConfig"
	RBLNServices_RblnSetConfig_FullMethodName            = "/rblnservices.RBLNServices/RblnSetConfig"
	RBLNServices_RblnListGroups_FullMethodName           = "/rblnservices.RBLNServices/RblnListGroups"
	RBLNServices_RblnCreateGroup_FullMethodName          = "/rblnservices.RBLNServices/RblnCreateGroup"
	RBLNServices_RblnDestroyGroup_FullMethodName         = "/rblnservices.RBLNServices/RblnDestroyGroup"
)

// RBLNServicesClient is the client API for RBLNServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RBLN API Services
type RBLNServicesClient interface {
	// search device list with device name (e.g. 'rbln0')
	GetDeviceList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Device], error)
	// like getDeviceList but lists serviceable devices only (excludes SR-IOV VFs)
	GetServiceableDeviceList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Device], error)
	// reset device from device name specified.
	ResetDevice(ctx context.Context, in *Device, opts ...grpc.CallOption) (*StatusMsg, error)
	// reset all device in system. it is equivalent with rsd reset.
	ResetAllDevice(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusMsg, error)
	// get version about firmware, smc and kernel.
	GetVersion(ctx context.Context, in *Device, opts ...grpc.CallOption) (*VersionInfo, error)
	// get hardware temperature and watt in device.
	GetHWInfo(ctx context.Context, in *Device, opts ...grpc.CallOption) (*HWInfo, error)
	// get device equipped ram size and memory size in use.
	GetMemoryInfo(ctx context.Context, in *Device, opts ...grpc.CallOption) (*MemoryInfo, error)
	// get device clock information.
	GetClockInfo(ctx context.Context, in *Device, opts ...grpc.CallOption) (*ClockInfo, error)
	// get hardware event generated and reported by kernel driver.
	GetEventInfo(ctx context.Context, in *Device, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventInfo], error)
	// get total device info. for specified device.
	// it includes device temperature, version, watt, memory info., clock info for specified device.
	GetTotalInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeviceInfo], error)
	// get utilization of NPU device
	GetUtilization(ctx context.Context, in *Device, opts ...grpc.CallOption) (*UtilInfo, error)
	// --- New RPCs (Rbln{Verb}{Resource} naming) ---
	// get topology info (NUMA, CPU affinity, RSD group, PCIe link) for devices
	RblnListTopology(ctx context.Context, in *DeviceFilter, opts ...grpc.CallOption) (*RblnListTopologyResponse, error)
	// list coredump entries for devices
	RblnListCoredumps(ctx context.Context, in *DeviceFilter, opts ...grpc.CallOption) (*RblnListCoredumpsResponse, error)
	// get a daemon runtime config value
	RblnGetConfig(ctx context.Context, in *RblnGetConfigRequest, opts ...grpc.CallOption) (*RblnGetConfigResponse, error)
	// set a daemon runtime config value
	RblnSetConfig(ctx context.Context, in *RblnSetConfigRequest, opts ...grpc.CallOption) (*RblnSetConfigResponse, error)
	// list all active RSD groups and their member devices
	RblnListGroups(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RblnListGroupsResponse, error)
	// create an RSD group with the specified devices
	RblnCreateGroup(ctx context.Context, in *RblnCreateGroupRequest, opts ...grpc.CallOption) (*RblnGroupOpResponse, error)
	// destroy an RSD group by group_id (-1 = all)
	RblnDestroyGroup(ctx context.Context, in *RblnDestroyGroupRequest, opts ...grpc.CallOption) (*RblnGroupOpResponse, error)
}

type rBLNServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewRBLNServicesClient(cc grpc.ClientConnInterface) RBLNServicesClient {
	return &rBLNServicesClient{cc}
}

func (c *rBLNServicesClient) GetDeviceList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Device], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RBLNServices_ServiceDesc.Streams[0], RBLNServices_GetDeviceList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, Device]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RBLNServices_GetDeviceListClient = grpc.ServerStreamingClient[Device]

func (c *rBLNServicesClient) GetServiceableDeviceList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Device], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RBLNServices_ServiceDesc.Streams[1], RBLNServices_GetServiceableDeviceList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, Device]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RBLNServices_GetServiceableDeviceListClient = grpc.ServerStreamingClient[Device]

func (c *rBLNServicesClient) ResetDevice(ctx context.Context, in *Device, opts ...grpc.CallOption) (*StatusMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusMsg)
	err := c.cc.Invoke(ctx, RBLNServices_ResetDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBLNServicesClient) ResetAllDevice(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusMsg)
	err := c.cc.Invoke(ctx, RBLNServices_ResetAllDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBLNServicesClient) GetVersion(ctx context.Context, in *Device, opts ...grpc.CallOption) (*VersionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionInfo)
	err := c.cc.Invoke(ctx, RBLNServices_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBLNServicesClient) GetHWInfo(ctx context.Context, in *Device, opts ...grpc.CallOption) (*HWInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HWInfo)
	err := c.cc.Invoke(ctx, RBLNServices_GetHWInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBLNServicesClient) GetMemoryInfo(ctx context.Context, in *Device, opts ...grpc.CallOption) (*MemoryInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryInfo)
	err := c.cc.Invoke(ctx, RBLNServices_GetMemoryInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBLNServicesClient) GetClockInfo(ctx context.Context, in *Device, opts ...grpc.CallOption) (*ClockInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClockInfo)
	err := c.cc.Invoke(ctx, RBLNServices_GetClockInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBLNServicesClient) GetEventInfo(ctx context.Context, in *Device, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventInfo], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RBLNServices_ServiceDesc.Streams[2], RBLNServices_GetEventInfo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Device, EventInfo]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RBLNServices_GetEventInfoClient = grpc.ServerStreamingClient[EventInfo]

func (c *rBLNServicesClient) GetTotalInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeviceInfo], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RBLNServices_ServiceDesc.Streams[3], RBLNServices_GetTotalInfo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, DeviceInfo]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RBLNServices_GetTotalInfoClient = grpc.ServerStreamingClient[DeviceInfo]

func (c *rBLNServicesClient) GetUtilization(ctx context.Context, in *Device, opts ...grpc.CallOption) (*UtilInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UtilInfo)
	err := c.cc.Invoke(ctx, RBLNServices_GetUtilization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBLNServicesClient) RblnListTopology(ctx context.Context, in *DeviceFilter, opts ...grpc.CallOption) (*RblnListTopologyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RblnListTopologyResponse)
	err := c.cc.Invoke(ctx, RBLNServices_RblnListTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBLNServicesClient) RblnListCoredumps(ctx context.Context, in *DeviceFilter, opts ...grpc.CallOption) (*RblnListCoredumpsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RblnListCoredumpsResponse)
	err := c.cc.Invoke(ctx, RBLNServices_RblnListCoredumps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBLNServicesClient) RblnGetConfig(ctx context.Context, in *RblnGetConfigRequest, opts ...grpc.CallOption) (*RblnGetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RblnGetConfigResponse)
	err := c.cc.Invoke(ctx, RBLNServices_RblnGetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBLNServicesClient) RblnSetConfig(ctx context.Context, in *RblnSetConfigRequest, opts ...grpc.CallOption) (*RblnSetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RblnSetConfigResponse)
	err := c.cc.Invoke(ctx, RBLNServices_RblnSetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBLNServicesClient) RblnListGroups(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RblnListGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RblnListGroupsResponse)
	err := c.cc.Invoke(ctx, RBLNServices_RblnListGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBLNServicesClient) RblnCreateGroup(ctx context.Context, in *RblnCreateGroupRequest, opts ...grpc.CallOption) (*RblnGroupOpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RblnGroupOpResponse)
	err := c.cc.Invoke(ctx, RBLNServices_RblnCreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBLNServicesClient) RblnDestroyGroup(ctx context.Context, in *RblnDestroyGroupRequest, opts ...grpc.CallOption) (*RblnGroupOpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RblnGroupOpResponse)
	err := c.cc.Invoke(ctx, RBLNServices_RblnDestroyGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RBLNServicesServer is the server API for RBLNServices service.
// All implementations must embed UnimplementedRBLNServicesServer
// for forward compatibility.
//
// RBLN API Services
type RBLNServicesServer interface {
	// search device list with device name (e.g. 'rbln0')
	GetDeviceList(*Empty, grpc.ServerStreamingServer[Device]) error
	// like getDeviceList but lists serviceable devices only (excludes SR-IOV VFs)
	GetServiceableDeviceList(*Empty, grpc.ServerStreamingServer[Device]) error
	// reset device from device name specified.
	ResetDevice(context.Context, *Device) (*StatusMsg, error)
	// reset all device in system. it is equivalent with rsd reset.
	ResetAllDevice(context.Context, *Empty) (*StatusMsg, error)
	// get version about firmware, smc and kernel.
	GetVersion(context.Context, *Device) (*VersionInfo, error)
	// get hardware temperature and watt in device.
	GetHWInfo(context.Context, *Device) (*HWInfo, error)
	// get device equipped ram size and memory size in use.
	GetMemoryInfo(context.Context, *Device) (*MemoryInfo, error)
	// get device clock information.
	GetClockInfo(context.Context, *Device) (*ClockInfo, error)
	// get hardware event generated and reported by kernel driver.
	GetEventInfo(*Device, grpc.ServerStreamingServer[EventInfo]) error
	// get total device info. for specified device.
	// it includes device temperature, version, watt, memory info., clock info for specified device.
	GetTotalInfo(*Empty, grpc.ServerStreamingServer[DeviceInfo]) error
	// get utilization of NPU device
	GetUtilization(context.Context, *Device) (*UtilInfo, error)
	// --- New RPCs (Rbln{Verb}{Resource} naming) ---
	// get topology info (NUMA, CPU affinity, RSD group, PCIe link) for devices
	RblnListTopology(context.Context, *DeviceFilter) (*RblnListTopologyResponse, error)
	// list coredump entries for devices
	RblnListCoredumps(context.Context, *DeviceFilter) (*RblnListCoredumpsResponse, error)
	// get a daemon runtime config value
	RblnGetConfig(context.Context, *RblnGetConfigRequest) (*RblnGetConfigResponse, error)
	// set a daemon runtime config value
	RblnSetConfig(context.Context, *RblnSetConfigRequest) (*RblnSetConfigResponse, error)
	// list all active RSD groups and their member devices
	RblnListGroups(context.Context, *Empty) (*RblnListGroupsResponse, error)
	// create an RSD group with the specified devices
	RblnCreateGroup(context.Context, *RblnCreateGroupRequest) (*RblnGroupOpResponse, error)
	// destroy an RSD group by group_id (-1 = all)
	RblnDestroyGroup(context.Context, *RblnDestroyGroupRequest) (*RblnGroupOpResponse, error)
	mustEmbedUnimplementedRBLNServicesServer()
}

// UnimplementedRBLNServicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRBLNServicesServer struct{}

func (UnimplementedRBLNServicesServer) GetDeviceList(*Empty, grpc.ServerStreamingServer[Device]) error {
	return status.Errorf(codes.Unimplemented, "method GetDeviceList not implemented")
}
func (UnimplementedRBLNServicesServer) GetServiceableDeviceList(*Empty, grpc.ServerStreamingServer[Device]) error {
	return status.Errorf(codes.Unimplemented, "method GetServiceableDeviceList not implemented")
}
func (UnimplementedRBLNServicesServer) ResetDevice(context.Context, *Device) (*StatusMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetDevice not implemented")
}
func (UnimplementedRBLNServicesServer) ResetAllDevice(context.Context, *Empty) (*StatusMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetAllDevice not implemented")
}
func (UnimplementedRBLNServicesServer) GetVersion(context.Context, *Device) (*VersionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedRBLNServicesServer) GetHWInfo(context.Context, *Device) (*HWInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHWInfo not implemented")
}
func (UnimplementedRBLNServicesServer) GetMemoryInfo(context.Context, *Device) (*MemoryInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemoryInfo not implemented")
}
func (UnimplementedRBLNServicesServer) GetClockInfo(context.Context, *Device) (*ClockInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClockInfo not implemented")
}
func (UnimplementedRBLNServicesServer) GetEventInfo(*Device, grpc.ServerStreamingServer[EventInfo]) error {
	return status.Errorf(codes.Unimplemented, "method GetEventInfo not implemented")
}
func (UnimplementedRBLNServicesServer) GetTotalInfo(*Empty, grpc.ServerStreamingServer[DeviceInfo]) error {
	return status.Errorf(codes.Unimplemented, "method GetTotalInfo not implemented")
}
func (UnimplementedRBLNServicesServer) GetUtilization(context.Context, *Device) (*UtilInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUtilization not implemented")
}
func (UnimplementedRBLNServicesServer) RblnListTopology(context.Context, *DeviceFilter) (*RblnListTopologyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RblnListTopology not implemented")
}
func (UnimplementedRBLNServicesServer) RblnListCoredumps(context.Context, *DeviceFilter) (*RblnListCoredumpsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RblnListCoredumps not implemented")
}
func (UnimplementedRBLNServicesServer) RblnGetConfig(context.Context, *RblnGetConfigRequest) (*RblnGetConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RblnGetConfig not implemented")
}
func (UnimplementedRBLNServicesServer) RblnSetConfig(context.Context, *RblnSetConfigRequest) (*RblnSetConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RblnSetConfig not implemented")
}
func (UnimplementedRBLNServicesServer) RblnListGroups(context.Context, *Empty) (*RblnListGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RblnListGroups not implemented")
}
func (UnimplementedRBLNServicesServer) RblnCreateGroup(context.Context, *RblnCreateGroupRequest) (*RblnGroupOpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RblnCreateGroup not implemented")
}
func (UnimplementedRBLNServicesServer) RblnDestroyGroup(context.Context, *RblnDestroyGroupRequest) (*RblnGroupOpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RblnDestroyGroup not implemented")
}
func (UnimplementedRBLNServicesServer) mustEmbedUnimplementedRBLNServicesServer() {}
func (UnimplementedRBLNServicesServer) testEmbeddedByValue()                      {}

// UnsafeRBLNServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RBLNServicesServer will
// result in compilation errors.
type UnsafeRBLNServicesServer interface {
	mustEmbedUnimplementedRBLNServicesServer()
}

func RegisterRBLNServicesServer(s grpc.ServiceRegistrar, srv RBLNServicesServer) {
	// If the following call pancis, it indicates UnimplementedRBLNServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RBLNServices_ServiceDesc, srv)
}

func _RBLNServices_GetDeviceList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RBLNServicesServer).GetDeviceList(m, &grpc.GenericServerStream[Empty, Device]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RBLNServices_GetDeviceListServer = grpc.ServerStreamingServer[Device]

func _RBLNServices_GetServiceableDeviceList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RBLNServicesServer).GetServiceableDeviceList(m, &grpc.GenericServerStream[Empty, Device]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RBLNServices_GetServiceableDeviceListServer = grpc.ServerStreamingServer[Device]

func _RBLNServices_ResetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBLNServicesServer).ResetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBLNServices_ResetDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBLNServicesServer).ResetDevice(ctx, req.(*Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBLNServices_ResetAllDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBLNServicesServer).ResetAllDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBLNServices_ResetAllDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBLNServicesServer).ResetAllDevice(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBLNServices_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBLNServicesServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBLNServices_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBLNServicesServer).GetVersion(ctx, req.(*Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBLNServices_GetHWInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBLNServicesServer).GetHWInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBLNServices_GetHWInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBLNServicesServer).GetHWInfo(ctx, req.(*Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBLNServices_GetMemoryInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBLNServicesServer).GetMemoryInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBLNServices_GetMemoryInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBLNServicesServer).GetMemoryInfo(ctx, req.(*Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBLNServices_GetClockInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBLNServicesServer).GetClockInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBLNServices_GetClockInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBLNServicesServer).GetClockInfo(ctx, req.(*Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBLNServices_GetEventInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Device)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RBLNServicesServer).GetEventInfo(m, &grpc.GenericServerStream[Device, EventInfo]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RBLNServices_GetEventInfoServer = grpc.ServerStreamingServer[EventInfo]

func _RBLNServices_GetTotalInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RBLNServicesServer).GetTotalInfo(m, &grpc.GenericServerStream[Empty, DeviceInfo]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RBLNServices_GetTotalInfoServer = grpc.ServerStreamingServer[DeviceInfo]

func _RBLNServices_GetUtilization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBLNServicesServer).GetUtilization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBLNServices_GetUtilization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBLNServicesServer).GetUtilization(ctx, req.(*Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBLNServices_RblnListTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBLNServicesServer).RblnListTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBLNServices_RblnListTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBLNServicesServer).RblnListTopology(ctx, req.(*DeviceFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBLNServices_RblnListCoredumps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBLNServicesServer).RblnListCoredumps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBLNServices_RblnListCoredumps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBLNServicesServer).RblnListCoredumps(ctx, req.(*DeviceFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBLNServices_RblnGetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RblnGetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBLNServicesServer).RblnGetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBLNServices_RblnGetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBLNServicesServer).RblnGetConfig(ctx, req.(*RblnGetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBLNServices_RblnSetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RblnSetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBLNServicesServer).RblnSetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBLNServices_RblnSetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBLNServicesServer).RblnSetConfig(ctx, req.(*RblnSetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBLNServices_RblnListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBLNServicesServer).RblnListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBLNServices_RblnListGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBLNServicesServer).RblnListGroups(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBLNServices_RblnCreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RblnCreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBLNServicesServer).RblnCreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBLNServices_RblnCreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBLNServicesServer).RblnCreateGroup(ctx, req.(*RblnCreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBLNServices_RblnDestroyGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RblnDestroyGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBLNServicesServer).RblnDestroyGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBLNServices_RblnDestroyGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBLNServicesServer).RblnDestroyGroup(ctx, req.(*RblnDestroyGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RBLNServices_ServiceDesc is the grpc.ServiceDesc for RBLNServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RBLNServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rblnservices.RBLNServices",
	HandlerType: (*RBLNServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "resetDevice",
			Handler:    _RBLNServices_ResetDevice_Handler,
		},
		{
			MethodName: "resetAllDevice",
			Handler:    _RBLNServices_ResetAllDevice_Handler,
		},
		{
			MethodName: "getVersion",
			Handler:    _RBLNServices_GetVersion_Handler,
		},
		{
			MethodName: "getHWInfo",
			Handler:    _RBLNServices_GetHWInfo_Handler,
		},
		{
			MethodName: "getMemoryInfo",
			Handler:    _RBLNServices_GetMemoryInfo_Handler,
		},
		{
			MethodName: "getClockInfo",
			Handler:    _RBLNServices_GetClockInfo_Handler,
		},
		{
			MethodName: "getUtilization",
			Handler:    _RBLNServices_GetUtilization_Handler,
		},
		{
			MethodName: "RblnListTopology",
			Handler:    _RBLNServices_RblnListTopology_Handler,
		},
		{
			MethodName: "RblnListCoredumps",
			Handler:    _RBLNServices_RblnListCoredumps_Handler,
		},
		{
			MethodName: "RblnGetConfig",
			Handler:    _RBLNServices_RblnGetConfig_Handler,
		},
		{
			MethodName: "RblnSetConfig",
			Handler:    _RBLNServices_RblnSetConfig_Handler,
		},
		{
			MethodName: "RblnListGroups",
			Handler:    _RBLNServices_RblnListGroups_Handler,
		},
		{
			MethodName: "RblnCreateGroup",
			Handler:    _RBLNServices_RblnCreateGroup_Handler,
		},
		{
			MethodName: "RblnDestroyGroup",
			Handler:    _RBLNServices_RblnDestroyGroup_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "getDeviceList",
			Handler:       _RBLNServices_GetDeviceList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "getServiceableDeviceList",
			Handler:       _RBLNServices_GetServiceableDeviceList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "getEventInfo",
			Handler:       _RBLNServices_GetEventInfo_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "getTotalInfo",
			Handler:       _RBLNServices_GetTotalInfo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rbln_services.proto",
}
