//
// [Rebellions Inc.]("Rebellions") CONFIDENTIAL
// Unpublished Copyright (c) 2021-2026 [Rebellions Inc.], All Rights Reserved.
//
// NOTICE: All information contained herein is, and remains the property of Rebellions.
// The intellectual and technical concepts contained herein are proprietary to Rebellions
// and may be covered by Republic of Korea, U.S., and other countries' Patents, patents
// in process, and are protected by trade secret or copyright law.
//
// Dissemination of this information or reproduction of this material is strictly forbidden
// unless prior written permission is obtained from Rebellions. Access to the source code
// contained herein is hereby forbidden to anyone except current Rebellions employees, managers
// or contractors who have executed Confidentiality and Non-disclosure agreements explicitly
// covering such access.
//
// The copyright notice above does not evidence any actual or intended publication or disclosure
// of this source code, which includes information that is confidential and/or proprietary, and
// is a trade secret, of Rebellions.
//
// ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC PERFORMANCE, OR PUBLIC DISPLAY OF OR
// THROUGH USE OF THIS SOURCE CODE WITHOUT THE EXPRESS WRITTEN CONSENT OF REBELLIONS IS STRICTLY
// PROHIBITED, AND IN VIOLATION OF APPLICABLE LAWS AND INTERNATIONAL TREATIES. THE RECEIPT OR
// POSSESSION OF THIS SOURCE CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS
// TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE, USE, OR SELL ANYTHING
// THAT IT MAY DESCRIBE, IN WHOLE OR IN PART.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: rbln_services.proto

package rblnservicespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	// indicates valid data in message
	Status_SUCCEED Status = 0
	// indicates invalid data in message
	Status_FAILED Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "SUCCEED",
		1: "FAILED",
	}
	Status_value = map[string]int32{
		"SUCCEED": 0,
		"FAILED":  1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_rbln_services_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_rbln_services_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{0}
}

// <pre><code>
// +====================================================================================+
// | Device State Machine Diagram                                                       |
// +====================================================================================+
// | [State Descriptions]                                                               |
// | 1. INIT   : Device initialization in progress.                                     |
// | 2. READY  : Device is ready for use (Init/Reset complete) or currently in use.     |
// | 3. BUSY   : Device reset request is being processed.                               |
// | 4. FAULT  : Reset request failed or unexpected device error occurred.              |
// | 5. FINISH : Device removal request is being processed.                             |
// +------------------------------------------------------------------------------------+
// | [State Diagram]                                                                    |
// |                                  ┌────────────┐                                    |
// |                                  │            │                                    |
// |                                  │    INIT    │                                    |
// |                                  │            │                                    |
// |                                  └─────┬──────┘                                    |
// |                                        │ (Init Complete)                           |
// |                                        ▼                                           |
// |           ┌────────────┐ (Dev    ┌────────────┐ (Remove  ┌────────────┐            |
// |           │            │ Fault)  │            │   Req)   │            │            |
// |           │   FAULT    │◀────────│   READY    │─────────▶│   FINISH   │            |
// |           │            │         │            │          │            │            |
// |           └───┬────────┘         └─────┬──────┘          └────────────┘            |
// |               │    ▲                   │  ▲                                        |
// |               │    │       (Reset Req) │  │ (Reset Succeed)                        |
// |               │    │                   │  │                                        |
// |               │    │(Reset Fail)       ▼  │                                        |
// |               │    │             ┌────────────┐                                    |
// |               │    └─────────────│            │                                    |
// |               │                  │    BUSY    │                                    |
// |               └─────────────────▶│            │                                    |
// |               (Reset Req)        └────────────┘                                    |
// +====================================================================================+
// </code></pre>
type DeviceStatus int32

const (
	// device is ready
	DeviceStatus_READY DeviceStatus = 0
	// device is busy
	DeviceStatus_BUSY DeviceStatus = 1
	// device is initialized, but not ready
	DeviceStatus_INIT DeviceStatus = 2
	// device is in fault state
	DeviceStatus_FAULT DeviceStatus = 3
	// device is finishing to remove
	DeviceStatus_FINISH DeviceStatus = 4
	// device not found
	DeviceStatus_NOT_FOUND DeviceStatus = 100
)

// Enum value maps for DeviceStatus.
var (
	DeviceStatus_name = map[int32]string{
		0:   "READY",
		1:   "BUSY",
		2:   "INIT",
		3:   "FAULT",
		4:   "FINISH",
		100: "NOT_FOUND",
	}
	DeviceStatus_value = map[string]int32{
		"READY":     0,
		"BUSY":      1,
		"INIT":      2,
		"FAULT":     3,
		"FINISH":    4,
		"NOT_FOUND": 100,
	}
)

func (x DeviceStatus) Enum() *DeviceStatus {
	p := new(DeviceStatus)
	*p = x
	return p
}

func (x DeviceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rbln_services_proto_enumTypes[1].Descriptor()
}

func (DeviceStatus) Type() protoreflect.EnumType {
	return &file_rbln_services_proto_enumTypes[1]
}

func (x DeviceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceStatus.Descriptor instead.
func (DeviceStatus) EnumDescriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{1}
}

// Deprecated since v3.x — will be removed in v4.0.0.
// EventInfo.event_type is now int32; match values against ENUM_RBLN_DMON_DATA_OUT_TYPE in
// rebellions/common/daemon.h instead of this enum.
// Migration: replace any EventType.Name(event.event_type) calls with a label lookup or direct integer comparison.
type EventType int32

const (
	// Deprecated: Marked as deprecated in rbln_services.proto.
	EventType_NO_RESPONSE EventType = 0
	// Deprecated: Marked as deprecated in rbln_services.proto.
	EventType_RESPONSE_REQUIRED EventType = 1
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "NO_RESPONSE",
		1: "RESPONSE_REQUIRED",
	}
	EventType_value = map[string]int32{
		"NO_RESPONSE":       0,
		"RESPONSE_REQUIRED": 1,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_rbln_services_proto_enumTypes[2].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_rbln_services_proto_enumTypes[2]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{2}
}

// Deprecated since v3.x — will be removed in v4.0.0.
// EventInfo.value is now int32; match values against ENUM_RBLN_DMON_EVENT_TYPE in
// rebellions/common/daemon.h instead of this enum.
// Migration: replace any EventSource.Name(event.value) calls with a label lookup or direct integer comparison.
type EventSource int32

const (
	// Deprecated: Marked as deprecated in rbln_services.proto.
	EventSource_SINGLE_HARD_RESET EventSource = 0
	// Deprecated: Marked as deprecated in rbln_services.proto.
	EventSource_RSD_HARD_RESET EventSource = 1
	// Deprecated: Marked as deprecated in rbln_services.proto.
	EventSource_TDR_EVENT EventSource = 2
	// Deprecated: Marked as deprecated in rbln_services.proto.
	EventSource_CP_EVENT EventSource = 3
	// Deprecated: Marked as deprecated in rbln_services.proto.
	EventSource_COREDUMP EventSource = 4
)

// Enum value maps for EventSource.
var (
	EventSource_name = map[int32]string{
		0: "SINGLE_HARD_RESET",
		1: "RSD_HARD_RESET",
		2: "TDR_EVENT",
		3: "CP_EVENT",
		4: "COREDUMP",
	}
	EventSource_value = map[string]int32{
		"SINGLE_HARD_RESET": 0,
		"RSD_HARD_RESET":    1,
		"TDR_EVENT":         2,
		"CP_EVENT":          3,
		"COREDUMP":          4,
	}
)

func (x EventSource) Enum() *EventSource {
	p := new(EventSource)
	*p = x
	return p
}

func (x EventSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventSource) Descriptor() protoreflect.EnumDescriptor {
	return file_rbln_services_proto_enumTypes[3].Descriptor()
}

func (EventSource) Type() protoreflect.EnumType {
	return &file_rbln_services_proto_enumTypes[3]
}

func (x EventSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventSource.Descriptor instead.
func (EventSource) EnumDescriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{3}
}

type StatusMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// just wrapper message for enum type data
	ErrStatus     Status `protobuf:"varint,1,opt,name=err_status,json=errStatus,proto3,enum=rblnservices.Status" json:"err_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusMsg) Reset() {
	*x = StatusMsg{}
	mi := &file_rbln_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusMsg) ProtoMessage() {}

func (x *StatusMsg) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusMsg.ProtoReflect.Descriptor instead.
func (*StatusMsg) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{0}
}

func (x *StatusMsg) GetErrStatus() Status {
	if x != nil {
		return x.ErrStatus
	}
	return Status_SUCCEED
}

type Device struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device name (e.g. 'rbln0')
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// device id (e.g. '1120', '1121')
	DevId string `protobuf:"bytes,2,opt,name=dev_id,json=devId,proto3" json:"dev_id,omitempty"`
	// device uuid (00000000-0000-0000-0000-000000000000 format)
	Uuid string `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// device pci bus id (e.g. 0000:47:00.0)
	PciBusId string `protobuf:"bytes,4,opt,name=pci_bus_id,json=pciBusId,proto3" json:"pci_bus_id,omitempty"`
	// card product name (e.g. 'RBLN-CA25')
	CardName string `protobuf:"bytes,5,opt,name=card_name,json=cardName,proto3" json:"card_name,omitempty"`
	// true when this device is an SR-IOV virtual function. Derived from the
	// authoritative PCI relationship (sysfs physfn link), not the device name.
	IsVf bool `protobuf:"varint,6,opt,name=is_vf,json=isVf,proto3" json:"is_vf,omitempty"`
	// for a VF, the device name of its parent physical function (e.g. 'rbln0');
	// empty for a PF. Lets clients render the PF/VF relationship without
	// guessing it from the device name.
	ParentName string `protobuf:"bytes,7,opt,name=parent_name,json=parentName,proto3" json:"parent_name,omitempty"`
	// number of SR-IOV VFs currently enabled on this PF. 0 for a VF or a PF
	// with SR-IOV disabled. A PF with num_vfs > 0 has been pulled from the
	// compute topology and is not directly usable; clients use this to avoid
	// presenting such a PF as a ready compute device.
	NumVfs        uint32 `protobuf:"varint,8,opt,name=num_vfs,json=numVfs,proto3" json:"num_vfs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_rbln_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{1}
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetDevId() string {
	if x != nil {
		return x.DevId
	}
	return ""
}

func (x *Device) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Device) GetPciBusId() string {
	if x != nil {
		return x.PciBusId
	}
	return ""
}

func (x *Device) GetCardName() string {
	if x != nil {
		return x.CardName
	}
	return ""
}

func (x *Device) GetIsVf() bool {
	if x != nil {
		return x.IsVf
	}
	return false
}

func (x *Device) GetParentName() string {
	if x != nil {
		return x.ParentName
	}
	return ""
}

func (x *Device) GetNumVfs() uint32 {
	if x != nil {
		return x.NumVfs
	}
	return 0
}

type ClockInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CP clock information (Mhz)
	Cp_0Clock int32 `protobuf:"varint,1,opt,name=cp_0_clock,json=cp0Clock,proto3" json:"cp_0_clock,omitempty"`
	// DNC1 clock information (Mhz)
	Dc_0Clock int32 `protobuf:"varint,2,opt,name=dc_0_clock,json=dc0Clock,proto3" json:"dc_0_clock,omitempty"`
	// DNC2 clock information (Mhz)
	Dc_1Clock int32 `protobuf:"varint,3,opt,name=dc_1_clock,json=dc1Clock,proto3" json:"dc_1_clock,omitempty"`
	// Bus clock information (Mhz)
	BusClock int32 `protobuf:"varint,4,opt,name=bus_clock,json=busClock,proto3" json:"bus_clock,omitempty"`
	// SHM clock information (Mhz)
	ShmClock int32 `protobuf:"varint,5,opt,name=shm_clock,json=shmClock,proto3" json:"shm_clock,omitempty"`
	// error status
	ErrStatus Status `protobuf:"varint,6,opt,name=err_status,json=errStatus,proto3,enum=rblnservices.Status" json:"err_status,omitempty"`
	// REBEL clock information
	Cp_1Clock     int32 `protobuf:"varint,7,opt,name=cp_1_clock,json=cp1Clock,proto3" json:"cp_1_clock,omitempty"`
	DramClock     int32 `protobuf:"varint,8,opt,name=dram_clock,json=dramClock,proto3" json:"dram_clock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClockInfo) Reset() {
	*x = ClockInfo{}
	mi := &file_rbln_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockInfo) ProtoMessage() {}

func (x *ClockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockInfo.ProtoReflect.Descriptor instead.
func (*ClockInfo) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{2}
}

func (x *ClockInfo) GetCp_0Clock() int32 {
	if x != nil {
		return x.Cp_0Clock
	}
	return 0
}

func (x *ClockInfo) GetDc_0Clock() int32 {
	if x != nil {
		return x.Dc_0Clock
	}
	return 0
}

func (x *ClockInfo) GetDc_1Clock() int32 {
	if x != nil {
		return x.Dc_1Clock
	}
	return 0
}

func (x *ClockInfo) GetBusClock() int32 {
	if x != nil {
		return x.BusClock
	}
	return 0
}

func (x *ClockInfo) GetShmClock() int32 {
	if x != nil {
		return x.ShmClock
	}
	return 0
}

func (x *ClockInfo) GetErrStatus() Status {
	if x != nil {
		return x.ErrStatus
	}
	return Status_SUCCEED
}

func (x *ClockInfo) GetCp_1Clock() int32 {
	if x != nil {
		return x.Cp_1Clock
	}
	return 0
}

func (x *ClockInfo) GetDramClock() int32 {
	if x != nil {
		return x.DramClock
	}
	return 0
}

type VersionInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Firmware version.
	FwVersion string `protobuf:"bytes,1,opt,name=fw_version,json=fwVersion,proto3" json:"fw_version,omitempty"`
	// Kernel driver version.
	DrvVersion string `protobuf:"bytes,2,opt,name=drv_version,json=drvVersion,proto3" json:"drv_version,omitempty"`
	// SMC version.
	SmcVersion string `protobuf:"bytes,3,opt,name=smc_version,json=smcVersion,proto3" json:"smc_version,omitempty"`
	// error status
	ErrStatus     Status `protobuf:"varint,4,opt,name=err_status,json=errStatus,proto3,enum=rblnservices.Status" json:"err_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionInfo) Reset() {
	*x = VersionInfo{}
	mi := &file_rbln_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionInfo) ProtoMessage() {}

func (x *VersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionInfo.ProtoReflect.Descriptor instead.
func (*VersionInfo) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{3}
}

func (x *VersionInfo) GetFwVersion() string {
	if x != nil {
		return x.FwVersion
	}
	return ""
}

func (x *VersionInfo) GetDrvVersion() string {
	if x != nil {
		return x.DrvVersion
	}
	return ""
}

func (x *VersionInfo) GetSmcVersion() string {
	if x != nil {
		return x.SmcVersion
	}
	return ""
}

func (x *VersionInfo) GetErrStatus() Status {
	if x != nil {
		return x.ErrStatus
	}
	return Status_SUCCEED
}

type HWInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// temperature in milli-degree Celsius unit.
	Temperature float32 `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// hardware power in micro-watt unit.
	Watt float32 `protobuf:"fixed32,2,opt,name=watt,proto3" json:"watt,omitempty"`
	// error status
	ErrStatus     Status `protobuf:"varint,3,opt,name=err_status,json=errStatus,proto3,enum=rblnservices.Status" json:"err_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HWInfo) Reset() {
	*x = HWInfo{}
	mi := &file_rbln_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HWInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HWInfo) ProtoMessage() {}

func (x *HWInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HWInfo.ProtoReflect.Descriptor instead.
func (*HWInfo) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{4}
}

func (x *HWInfo) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *HWInfo) GetWatt() float32 {
	if x != nil {
		return x.Watt
	}
	return 0
}

func (x *HWInfo) GetErrStatus() Status {
	if x != nil {
		return x.ErrStatus
	}
	return Status_SUCCEED
}

type MemoryInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device total memory (GB unit)
	TotalMem float32 `protobuf:"fixed32,1,opt,name=total_mem,json=totalMem,proto3" json:"total_mem,omitempty"`
	// device memory in use (GB unit)
	UsedMem float32 `protobuf:"fixed32,2,opt,name=used_mem,json=usedMem,proto3" json:"used_mem,omitempty"`
	// error status
	ErrStatus     Status `protobuf:"varint,3,opt,name=err_status,json=errStatus,proto3,enum=rblnservices.Status" json:"err_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryInfo) Reset() {
	*x = MemoryInfo{}
	mi := &file_rbln_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInfo) ProtoMessage() {}

func (x *MemoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInfo.ProtoReflect.Descriptor instead.
func (*MemoryInfo) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{5}
}

func (x *MemoryInfo) GetTotalMem() float32 {
	if x != nil {
		return x.TotalMem
	}
	return 0
}

func (x *MemoryInfo) GetUsedMem() float32 {
	if x != nil {
		return x.UsedMem
	}
	return 0
}

func (x *MemoryInfo) GetErrStatus() Status {
	if x != nil {
		return x.ErrStatus
	}
	return Status_SUCCEED
}

type UtilInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// utilization(percent) of device processing unit
	Utilization float32 `protobuf:"fixed32,1,opt,name=utilization,proto3" json:"utilization,omitempty"`
	// error status
	ErrStatus     Status `protobuf:"varint,2,opt,name=err_status,json=errStatus,proto3,enum=rblnservices.Status" json:"err_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UtilInfo) Reset() {
	*x = UtilInfo{}
	mi := &file_rbln_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtilInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtilInfo) ProtoMessage() {}

func (x *UtilInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtilInfo.ProtoReflect.Descriptor instead.
func (*UtilInfo) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{6}
}

func (x *UtilInfo) GetUtilization() float32 {
	if x != nil {
		return x.Utilization
	}
	return 0
}

func (x *UtilInfo) GetErrStatus() Status {
	if x != nil {
		return x.ErrStatus
	}
	return Status_SUCCEED
}

type EventInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device name
	DevName string `protobuf:"bytes,1,opt,name=dev_name,json=devName,proto3" json:"dev_name,omitempty"`
	// event type
	EventType int32 `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// event source value
	Value int32 `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	// sub event value
	SubValue int32 `protobuf:"varint,4,opt,name=sub_value,json=subValue,proto3" json:"sub_value,omitempty"`
	// event trigger time (uptime)
	KernelTime float64 `protobuf:"fixed64,5,opt,name=kernel_time,json=kernelTime,proto3" json:"kernel_time,omitempty"`
	// UTC time with host time zone.
	UtcTime       string `protobuf:"bytes,6,opt,name=utc_time,json=utcTime,proto3" json:"utc_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventInfo) Reset() {
	*x = EventInfo{}
	mi := &file_rbln_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventInfo) ProtoMessage() {}

func (x *EventInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventInfo.ProtoReflect.Descriptor instead.
func (*EventInfo) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{7}
}

func (x *EventInfo) GetDevName() string {
	if x != nil {
		return x.DevName
	}
	return ""
}

func (x *EventInfo) GetEventType() int32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *EventInfo) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *EventInfo) GetSubValue() int32 {
	if x != nil {
		return x.SubValue
	}
	return 0
}

func (x *EventInfo) GetKernelTime() float64 {
	if x != nil {
		return x.KernelTime
	}
	return 0
}

func (x *EventInfo) GetUtcTime() string {
	if x != nil {
		return x.UtcTime
	}
	return ""
}

type DeviceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// device uuid
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// device total memory (GB unit)
	TotalMem float32 `protobuf:"fixed32,3,opt,name=total_mem,json=totalMem,proto3" json:"total_mem,omitempty"`
	// device memory in use (GB unit)
	UsedMem float32 `protobuf:"fixed32,4,opt,name=used_mem,json=usedMem,proto3" json:"used_mem,omitempty"`
	// temperature in milli-degree Celsius unit.
	Temperature float32 `protobuf:"fixed32,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// hardware power currently consumed in micro-watt
	Watt float32 `protobuf:"fixed32,6,opt,name=watt,proto3" json:"watt,omitempty"`
	// firmware version
	FwVersion string `protobuf:"bytes,7,opt,name=fw_version,json=fwVersion,proto3" json:"fw_version,omitempty"`
	// kernel driver version
	DrvVersion string `protobuf:"bytes,8,opt,name=drv_version,json=drvVersion,proto3" json:"drv_version,omitempty"`
	// device utilization
	Utilization float32 `protobuf:"fixed32,9,opt,name=utilization,proto3" json:"utilization,omitempty"`
	// error status
	ErrStatus Status `protobuf:"varint,10,opt,name=err_status,json=errStatus,proto3,enum=rblnservices.Status" json:"err_status,omitempty"`
	// device status
	DevStatus DeviceStatus `protobuf:"varint,11,opt,name=dev_status,json=devStatus,proto3,enum=rblnservices.DeviceStatus" json:"dev_status,omitempty"`
	// device p-state
	PState        int32 `protobuf:"varint,12,opt,name=p_state,json=pState,proto3" json:"p_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_rbln_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DeviceInfo) GetTotalMem() float32 {
	if x != nil {
		return x.TotalMem
	}
	return 0
}

func (x *DeviceInfo) GetUsedMem() float32 {
	if x != nil {
		return x.UsedMem
	}
	return 0
}

func (x *DeviceInfo) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *DeviceInfo) GetWatt() float32 {
	if x != nil {
		return x.Watt
	}
	return 0
}

func (x *DeviceInfo) GetFwVersion() string {
	if x != nil {
		return x.FwVersion
	}
	return ""
}

func (x *DeviceInfo) GetDrvVersion() string {
	if x != nil {
		return x.DrvVersion
	}
	return ""
}

func (x *DeviceInfo) GetUtilization() float32 {
	if x != nil {
		return x.Utilization
	}
	return 0
}

func (x *DeviceInfo) GetErrStatus() Status {
	if x != nil {
		return x.ErrStatus
	}
	return Status_SUCCEED
}

func (x *DeviceInfo) GetDevStatus() DeviceStatus {
	if x != nil {
		return x.DevStatus
	}
	return DeviceStatus_READY
}

func (x *DeviceInfo) GetPState() int32 {
	if x != nil {
		return x.PState
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_rbln_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{9}
}

// Per-item error detail. Empty (default) = success.
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_rbln_services_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{10}
}

func (x *ErrorDetail) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Server-side device filter. Empty = all devices.
// device_ids and group_ids are mutually exclusive;
// server ignores group_ids if device_ids is present.
type DeviceFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceIds     []int32                `protobuf:"varint,1,rep,packed,name=device_ids,json=deviceIds,proto3" json:"device_ids,omitempty"`
	GroupIds      []int32                `protobuf:"varint,2,rep,packed,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceFilter) Reset() {
	*x = DeviceFilter{}
	mi := &file_rbln_services_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceFilter) ProtoMessage() {}

func (x *DeviceFilter) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceFilter.ProtoReflect.Descriptor instead.
func (*DeviceFilter) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{11}
}

func (x *DeviceFilter) GetDeviceIds() []int32 {
	if x != nil {
		return x.DeviceIds
	}
	return nil
}

func (x *DeviceFilter) GetGroupIds() []int32 {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

type TopologyEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceName    string                 `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	PciBusId      string                 `protobuf:"bytes,2,opt,name=pci_bus_id,json=pciBusId,proto3" json:"pci_bus_id,omitempty"`
	NumaNode      int32                  `protobuf:"varint,3,opt,name=numa_node,json=numaNode,proto3" json:"numa_node,omitempty"`
	LocalCpulist  string                 `protobuf:"bytes,4,opt,name=local_cpulist,json=localCpulist,proto3" json:"local_cpulist,omitempty"`
	RsdGroup      string                 `protobuf:"bytes,5,opt,name=rsd_group,json=rsdGroup,proto3" json:"rsd_group,omitempty"`
	PcieLinkSpeed string                 `protobuf:"bytes,6,opt,name=pcie_link_speed,json=pcieLinkSpeed,proto3" json:"pcie_link_speed,omitempty"`
	PcieLinkWidth string                 `protobuf:"bytes,7,opt,name=pcie_link_width,json=pcieLinkWidth,proto3" json:"pcie_link_width,omitempty"`
	Error         *ErrorDetail           `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyEntry) Reset() {
	*x = TopologyEntry{}
	mi := &file_rbln_services_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyEntry) ProtoMessage() {}

func (x *TopologyEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyEntry.ProtoReflect.Descriptor instead.
func (*TopologyEntry) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{12}
}

func (x *TopologyEntry) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *TopologyEntry) GetPciBusId() string {
	if x != nil {
		return x.PciBusId
	}
	return ""
}

func (x *TopologyEntry) GetNumaNode() int32 {
	if x != nil {
		return x.NumaNode
	}
	return 0
}

func (x *TopologyEntry) GetLocalCpulist() string {
	if x != nil {
		return x.LocalCpulist
	}
	return ""
}

func (x *TopologyEntry) GetRsdGroup() string {
	if x != nil {
		return x.RsdGroup
	}
	return ""
}

func (x *TopologyEntry) GetPcieLinkSpeed() string {
	if x != nil {
		return x.PcieLinkSpeed
	}
	return ""
}

func (x *TopologyEntry) GetPcieLinkWidth() string {
	if x != nil {
		return x.PcieLinkWidth
	}
	return ""
}

func (x *TopologyEntry) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type RblnListTopologyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*TopologyEntry       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RblnListTopologyResponse) Reset() {
	*x = RblnListTopologyResponse{}
	mi := &file_rbln_services_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RblnListTopologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RblnListTopologyResponse) ProtoMessage() {}

func (x *RblnListTopologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RblnListTopologyResponse.ProtoReflect.Descriptor instead.
func (*RblnListTopologyResponse) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{13}
}

func (x *RblnListTopologyResponse) GetEntries() []*TopologyEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CoredumpEntry struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	DeviceName string                 `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	Timestamp  string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Path       string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// Fields below are read from the per-coredump `meta` INI file written
	// alongside fw.log/boot.log. They are best-effort: an older daemon, an
	// older coredump dir without a meta file, or a missing/corrupt meta
	// file leaves them at their proto3 default (empty string / 0).
	Situation     string       `protobuf:"bytes,4,opt,name=situation,proto3" json:"situation,omitempty"`                           // CDP situation name, e.g. "RESET" or "MANUAL"
	Version       uint32       `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`                              // coredump header version (1 or 2)
	TimestampUtc  string       `protobuf:"bytes,6,opt,name=timestamp_utc,json=timestampUtc,proto3" json:"timestamp_utc,omitempty"` // ISO-8601 UTC, e.g. "2026-04-29T04:30:53.554Z"
	AsicType      uint32       `protobuf:"varint,7,opt,name=asic_type,json=asicType,proto3" json:"asic_type,omitempty"`            // ASIC type id from coredump header (KMD-emitted); 0 if unavailable
	Error         *ErrorDetail `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoredumpEntry) Reset() {
	*x = CoredumpEntry{}
	mi := &file_rbln_services_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoredumpEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoredumpEntry) ProtoMessage() {}

func (x *CoredumpEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoredumpEntry.ProtoReflect.Descriptor instead.
func (*CoredumpEntry) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{14}
}

func (x *CoredumpEntry) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *CoredumpEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *CoredumpEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CoredumpEntry) GetSituation() string {
	if x != nil {
		return x.Situation
	}
	return ""
}

func (x *CoredumpEntry) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CoredumpEntry) GetTimestampUtc() string {
	if x != nil {
		return x.TimestampUtc
	}
	return ""
}

func (x *CoredumpEntry) GetAsicType() uint32 {
	if x != nil {
		return x.AsicType
	}
	return 0
}

func (x *CoredumpEntry) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type RblnListCoredumpsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*CoredumpEntry       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RblnListCoredumpsResponse) Reset() {
	*x = RblnListCoredumpsResponse{}
	mi := &file_rbln_services_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RblnListCoredumpsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RblnListCoredumpsResponse) ProtoMessage() {}

func (x *RblnListCoredumpsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RblnListCoredumpsResponse.ProtoReflect.Descriptor instead.
func (*RblnListCoredumpsResponse) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{15}
}

func (x *RblnListCoredumpsResponse) GetEntries() []*CoredumpEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type RblnGetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RblnGetConfigRequest) Reset() {
	*x = RblnGetConfigRequest{}
	mi := &file_rbln_services_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RblnGetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RblnGetConfigRequest) ProtoMessage() {}

func (x *RblnGetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RblnGetConfigRequest.ProtoReflect.Descriptor instead.
func (*RblnGetConfigRequest) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{16}
}

func (x *RblnGetConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type RblnGetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Error         *ErrorDetail           `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RblnGetConfigResponse) Reset() {
	*x = RblnGetConfigResponse{}
	mi := &file_rbln_services_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RblnGetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RblnGetConfigResponse) ProtoMessage() {}

func (x *RblnGetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RblnGetConfigResponse.ProtoReflect.Descriptor instead.
func (*RblnGetConfigResponse) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{17}
}

func (x *RblnGetConfigResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RblnGetConfigResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *RblnGetConfigResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type RblnSetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RblnSetConfigRequest) Reset() {
	*x = RblnSetConfigRequest{}
	mi := &file_rbln_services_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RblnSetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RblnSetConfigRequest) ProtoMessage() {}

func (x *RblnSetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RblnSetConfigRequest.ProtoReflect.Descriptor instead.
func (*RblnSetConfigRequest) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{18}
}

func (x *RblnSetConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RblnSetConfigRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RblnSetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *ErrorDetail           `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RblnSetConfigResponse) Reset() {
	*x = RblnSetConfigResponse{}
	mi := &file_rbln_services_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RblnSetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RblnSetConfigResponse) ProtoMessage() {}

func (x *RblnSetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RblnSetConfigResponse.ProtoReflect.Descriptor instead.
func (*RblnSetConfigResponse) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{19}
}

func (x *RblnSetConfigResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type GroupEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	DeviceNames   []string               `protobuf:"bytes,3,rep,name=device_names,json=deviceNames,proto3" json:"device_names,omitempty"`
	Error         *ErrorDetail           `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupEntry) Reset() {
	*x = GroupEntry{}
	mi := &file_rbln_services_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupEntry) ProtoMessage() {}

func (x *GroupEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupEntry.ProtoReflect.Descriptor instead.
func (*GroupEntry) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{20}
}

func (x *GroupEntry) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupEntry) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupEntry) GetDeviceNames() []string {
	if x != nil {
		return x.DeviceNames
	}
	return nil
}

func (x *GroupEntry) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type RblnListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*GroupEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RblnListGroupsResponse) Reset() {
	*x = RblnListGroupsResponse{}
	mi := &file_rbln_services_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RblnListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RblnListGroupsResponse) ProtoMessage() {}

func (x *RblnListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RblnListGroupsResponse.ProtoReflect.Descriptor instead.
func (*RblnListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{21}
}

func (x *RblnListGroupsResponse) GetEntries() []*GroupEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type RblnCreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	DeviceIds     []int32                `protobuf:"varint,2,rep,packed,name=device_ids,json=deviceIds,proto3" json:"device_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RblnCreateGroupRequest) Reset() {
	*x = RblnCreateGroupRequest{}
	mi := &file_rbln_services_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RblnCreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RblnCreateGroupRequest) ProtoMessage() {}

func (x *RblnCreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RblnCreateGroupRequest.ProtoReflect.Descriptor instead.
func (*RblnCreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{22}
}

func (x *RblnCreateGroupRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *RblnCreateGroupRequest) GetDeviceIds() []int32 {
	if x != nil {
		return x.DeviceIds
	}
	return nil
}

// group_id = -1 is a sentinel for "destroy all groups"
type RblnDestroyGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RblnDestroyGroupRequest) Reset() {
	*x = RblnDestroyGroupRequest{}
	mi := &file_rbln_services_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RblnDestroyGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RblnDestroyGroupRequest) ProtoMessage() {}

func (x *RblnDestroyGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RblnDestroyGroupRequest.ProtoReflect.Descriptor instead.
func (*RblnDestroyGroupRequest) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{23}
}

func (x *RblnDestroyGroupRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type RblnGroupOpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *ErrorDetail           `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RblnGroupOpResponse) Reset() {
	*x = RblnGroupOpResponse{}
	mi := &file_rbln_services_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RblnGroupOpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RblnGroupOpResponse) ProtoMessage() {}

func (x *RblnGroupOpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbln_services_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RblnGroupOpResponse.ProtoReflect.Descriptor instead.
func (*RblnGroupOpResponse) Descriptor() ([]byte, []int) {
	return file_rbln_services_proto_rawDescGZIP(), []int{24}
}

func (x *RblnGroupOpResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_rbln_services_proto protoreflect.FileDescriptor

const file_rbln_services_proto_rawDesc = "" +
	"\n" +
	"\x13rbln_services.proto\x12\frblnservices\"@\n" +
	"\tStatusMsg\x123\n" +
	"\n" +
	"err_status\x18\x01 \x01(\x0e2\x14.rblnservices.StatusR\terrStatus\"\xd1\x01\n" +
	"\x06Device\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06dev_id\x18\x02 \x01(\tR\x05devId\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\tR\x04uuid\x12\x1c\n" +
	"\n" +
	"pci_bus_id\x18\x04 \x01(\tR\bpciBusId\x12\x1b\n" +
	"\tcard_name\x18\x05 \x01(\tR\bcardName\x12\x13\n" +
	"\x05is_vf\x18\x06 \x01(\bR\x04isVf\x12\x1f\n" +
	"\vparent_name\x18\a \x01(\tR\n" +
	"parentName\x12\x17\n" +
	"\anum_vfs\x18\b \x01(\rR\x06numVfs\"\x91\x02\n" +
	"\tClockInfo\x12\x1c\n" +
	"\n" +
	"cp_0_clock\x18\x01 \x01(\x05R\bcp0Clock\x12\x1c\n" +
	"\n" +
	"dc_0_clock\x18\x02 \x01(\x05R\bdc0Clock\x12\x1c\n" +
	"\n" +
	"dc_1_clock\x18\x03 \x01(\x05R\bdc1Clock\x12\x1b\n" +
	"\tbus_clock\x18\x04 \x01(\x05R\bbusClock\x12\x1b\n" +
	"\tshm_clock\x18\x05 \x01(\x05R\bshmClock\x123\n" +
	"\n" +
	"err_status\x18\x06 \x01(\x0e2\x14.rblnservices.StatusR\terrStatus\x12\x1c\n" +
	"\n" +
	"cp_1_clock\x18\a \x01(\x05R\bcp1Clock\x12\x1d\n" +
	"\n" +
	"dram_clock\x18\b \x01(\x05R\tdramClock\"\xa3\x01\n" +
	"\vVersionInfo\x12\x1d\n" +
	"\n" +
	"fw_version\x18\x01 \x01(\tR\tfwVersion\x12\x1f\n" +
	"\vdrv_version\x18\x02 \x01(\tR\n" +
	"drvVersion\x12\x1f\n" +
	"\vsmc_version\x18\x03 \x01(\tR\n" +
	"smcVersion\x123\n" +
	"\n" +
	"err_status\x18\x04 \x01(\x0e2\x14.rblnservices.StatusR\terrStatus\"s\n" +
	"\x06HWInfo\x12 \n" +
	"\vtemperature\x18\x01 \x01(\x02R\vtemperature\x12\x12\n" +
	"\x04watt\x18\x02 \x01(\x02R\x04watt\x123\n" +
	"\n" +
	"err_status\x18\x03 \x01(\x0e2\x14.rblnservices.StatusR\terrStatus\"y\n" +
	"\n" +
	"MemoryInfo\x12\x1b\n" +
	"\ttotal_mem\x18\x01 \x01(\x02R\btotalMem\x12\x19\n" +
	"\bused_mem\x18\x02 \x01(\x02R\ausedMem\x123\n" +
	"\n" +
	"err_status\x18\x03 \x01(\x0e2\x14.rblnservices.StatusR\terrStatus\"a\n" +
	"\bUtilInfo\x12 \n" +
	"\vutilization\x18\x01 \x01(\x02R\vutilization\x123\n" +
	"\n" +
	"err_status\x18\x02 \x01(\x0e2\x14.rblnservices.StatusR\terrStatus\"\xb4\x01\n" +
	"\tEventInfo\x12\x19\n" +
	"\bdev_name\x18\x01 \x01(\tR\adevName\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x05R\teventType\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x05R\x05value\x12\x1b\n" +
	"\tsub_value\x18\x04 \x01(\x05R\bsubValue\x12\x1f\n" +
	"\vkernel_time\x18\x05 \x01(\x01R\n" +
	"kernelTime\x12\x19\n" +
	"\butc_time\x18\x06 \x01(\tR\autcTime\"\x8d\x03\n" +
	"\n" +
	"DeviceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1b\n" +
	"\ttotal_mem\x18\x03 \x01(\x02R\btotalMem\x12\x19\n" +
	"\bused_mem\x18\x04 \x01(\x02R\ausedMem\x12 \n" +
	"\vtemperature\x18\x05 \x01(\x02R\vtemperature\x12\x12\n" +
	"\x04watt\x18\x06 \x01(\x02R\x04watt\x12\x1d\n" +
	"\n" +
	"fw_version\x18\a \x01(\tR\tfwVersion\x12\x1f\n" +
	"\vdrv_version\x18\b \x01(\tR\n" +
	"drvVersion\x12 \n" +
	"\vutilization\x18\t \x01(\x02R\vutilization\x123\n" +
	"\n" +
	"err_status\x18\n" +
	" \x01(\x0e2\x14.rblnservices.StatusR\terrStatus\x129\n" +
	"\n" +
	"dev_status\x18\v \x01(\x0e2\x1a.rblnservices.DeviceStatusR\tdevStatus\x12\x17\n" +
	"\ap_state\x18\f \x01(\x05R\x06pState\"\a\n" +
	"\x05Empty\";\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"J\n" +
	"\fDeviceFilter\x12\x1d\n" +
	"\n" +
	"device_ids\x18\x01 \x03(\x05R\tdeviceIds\x12\x1b\n" +
	"\tgroup_ids\x18\x02 \x03(\x05R\bgroupIds\"\xae\x02\n" +
	"\rTopologyEntry\x12\x1f\n" +
	"\vdevice_name\x18\x01 \x01(\tR\n" +
	"deviceName\x12\x1c\n" +
	"\n" +
	"pci_bus_id\x18\x02 \x01(\tR\bpciBusId\x12\x1b\n" +
	"\tnuma_node\x18\x03 \x01(\x05R\bnumaNode\x12#\n" +
	"\rlocal_cpulist\x18\x04 \x01(\tR\flocalCpulist\x12\x1b\n" +
	"\trsd_group\x18\x05 \x01(\tR\brsdGroup\x12&\n" +
	"\x0fpcie_link_speed\x18\x06 \x01(\tR\rpcieLinkSpeed\x12&\n" +
	"\x0fpcie_link_width\x18\a \x01(\tR\rpcieLinkWidth\x12/\n" +
	"\x05error\x18\x0f \x01(\v2\x19.rblnservices.ErrorDetailR\x05error\"Q\n" +
	"\x18RblnListTopologyResponse\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.rblnservices.TopologyEntryR\aentries\"\x8d\x02\n" +
	"\rCoredumpEntry\x12\x1f\n" +
	"\vdevice_name\x18\x01 \x01(\tR\n" +
	"deviceName\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1c\n" +
	"\tsituation\x18\x04 \x01(\tR\tsituation\x12\x18\n" +
	"\aversion\x18\x05 \x01(\rR\aversion\x12#\n" +
	"\rtimestamp_utc\x18\x06 \x01(\tR\ftimestampUtc\x12\x1b\n" +
	"\tasic_type\x18\a \x01(\rR\basicType\x12/\n" +
	"\x05error\x18\x0f \x01(\v2\x19.rblnservices.ErrorDetailR\x05error\"R\n" +
	"\x19RblnListCoredumpsResponse\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.rblnservices.CoredumpEntryR\aentries\"(\n" +
	"\x14RblnGetConfigRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"p\n" +
	"\x15RblnGetConfigResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12/\n" +
	"\x05error\x18\x0f \x01(\v2\x19.rblnservices.ErrorDetailR\x05error\">\n" +
	"\x14RblnSetConfigRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"H\n" +
	"\x15RblnSetConfigResponse\x12/\n" +
	"\x05error\x18\x0f \x01(\v2\x19.rblnservices.ErrorDetailR\x05error\"\x9a\x01\n" +
	"\n" +
	"GroupEntry\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12!\n" +
	"\fdevice_names\x18\x03 \x03(\tR\vdeviceNames\x12/\n" +
	"\x05error\x18\x0f \x01(\v2\x19.rblnservices.ErrorDetailR\x05error\"L\n" +
	"\x16RblnListGroupsResponse\x122\n" +
	"\aentries\x18\x01 \x03(\v2\x18.rblnservices.GroupEntryR\aentries\"R\n" +
	"\x16RblnCreateGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\x12\x1d\n" +
	"\n" +
	"device_ids\x18\x02 \x03(\x05R\tdeviceIds\"4\n" +
	"\x17RblnDestroyGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\"F\n" +
	"\x13RblnGroupOpResponse\x12/\n" +
	"\x05error\x18\x0f \x01(\v2\x19.rblnservices.ErrorDetailR\x05error*!\n" +
	"\x06Status\x12\v\n" +
	"\aSUCCEED\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01*_\n" +
	"\fDeviceStatus\x12\t\n" +
	"\x05READY\x10\x00\x12\b\n" +
	"\x04BUSY\x10\x01\x12\b\n" +
	"\x04INIT\x10\x02\x12\t\n" +
	"\x05FAULT\x10\x03\x12\n" +
	"\n" +
	"\x06FINISH\x10\x04\x12\r\n" +
	"\tNOT_FOUND\x10d\"\x04\b\x05\x10c\"\x04\be\x10\x7f*;\n" +
	"\tEventType\x12\x13\n" +
	"\vNO_RESPONSE\x10\x00\x1a\x02\b\x01\x12\x19\n" +
	"\x11RESPONSE_REQUIRED\x10\x01\x1a\x02\b\x01*w\n" +
	"\vEventSource\x12\x19\n" +
	"\x11SINGLE_HARD_RESET\x10\x00\x1a\x02\b\x01\x12\x16\n" +
	"\x0eRSD_HARD_RESET\x10\x01\x1a\x02\b\x01\x12\x11\n" +
	"\tTDR_EVENT\x10\x02\x1a\x02\b\x01\x12\x10\n" +
	"\bCP_EVENT\x10\x03\x1a\x02\b\x01\x12\x10\n" +
	"\bCOREDUMP\x10\x04\x1a\x02\b\x012\xde\n" +
	"\n" +
	"\fRBLNServices\x12>\n" +
	"\rgetDeviceList\x12\x13.rblnservices.Empty\x1a\x14.rblnservices.Device\"\x000\x01\x12I\n" +
	"\x18getServiceableDeviceList\x12\x13.rblnservices.Empty\x1a\x14.rblnservices.Device\"\x000\x01\x12>\n" +
	"\vresetDevice\x12\x14.rblnservices.Device\x1a\x17.rblnservices.StatusMsg\"\x00\x12@\n" +
	"\x0eresetAllDevice\x12\x13.rblnservices.Empty\x1a\x17.rblnservices.StatusMsg\"\x00\x12?\n" +
	"\n" +
	"getVersion\x12\x14.rblnservices.Device\x1a\x19.rblnservices.VersionInfo\"\x00\x129\n" +
	"\tgetHWInfo\x12\x14.rblnservices.Device\x1a\x14.rblnservices.HWInfo\"\x00\x12A\n" +
	"\rgetMemoryInfo\x12\x14.rblnservices.Device\x1a\x18.rblnservices.MemoryInfo\"\x00\x12?\n" +
	"\fgetClockInfo\x12\x14.rblnservices.Device\x1a\x17.rblnservices.ClockInfo\"\x00\x12A\n" +
	"\fgetEventInfo\x12\x14.rblnservices.Device\x1a\x17.rblnservices.EventInfo\"\x000\x01\x12A\n" +
	"\fgetTotalInfo\x12\x13.rblnservices.Empty\x1a\x18.rblnservices.DeviceInfo\"\x000\x01\x12@\n" +
	"\x0egetUtilization\x12\x14.rblnservices.Device\x1a\x16.rblnservices.UtilInfo\"\x00\x12X\n" +
	"\x10RblnListTopology\x12\x1a.rblnservices.DeviceFilter\x1a&.rblnservices.RblnListTopologyResponse\"\x00\x12Z\n" +
	"\x11RblnListCoredumps\x12\x1a.rblnservices.DeviceFilter\x1a'.rblnservices.RblnListCoredumpsResponse\"\x00\x12Z\n" +
	"\rRblnGetConfig\x12\".rblnservices.RblnGetConfigRequest\x1a#.rblnservices.RblnGetConfigResponse\"\x00\x12Z\n" +
	"\rRblnSetConfig\x12\".rblnservices.RblnSetConfigRequest\x1a#.rblnservices.RblnSetConfigResponse\"\x00\x12M\n" +
	"\x0eRblnListGroups\x12\x13.rblnservices.Empty\x1a$.rblnservices.RblnListGroupsResponse\"\x00\x12\\\n" +
	"\x0fRblnCreateGroup\x12$.rblnservices.RblnCreateGroupRequest\x1a!.rblnservices.RblnGroupOpResponse\"\x00\x12^\n" +
	"\x10RblnDestroyGroup\x12%.rblnservices.RblnDestroyGroupRequest\x1a!.rblnservices.RblnGroupOpResponse\"\x00BCZAgithub.com/rebellions-sw/rbln-metrics-exporter/pkg/rblnservicespbb\x06proto3"

var (
	file_rbln_services_proto_rawDescOnce sync.Once
	file_rbln_services_proto_rawDescData []byte
)

func file_rbln_services_proto_rawDescGZIP() []byte {
	file_rbln_services_proto_rawDescOnce.Do(func() {
		file_rbln_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rbln_services_proto_rawDesc), len(file_rbln_services_proto_rawDesc)))
	})
	return file_rbln_services_proto_rawDescData
}

var file_rbln_services_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_rbln_services_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_rbln_services_proto_goTypes = []any{
	(Status)(0),                       // 0: rblnservices.Status
	(DeviceStatus)(0),                 // 1: rblnservices.DeviceStatus
	(EventType)(0),                    // 2: rblnservices.EventType
	(EventSource)(0),                  // 3: rblnservices.EventSource
	(*StatusMsg)(nil),                 // 4: rblnservices.StatusMsg
	(*Device)(nil),                    // 5: rblnservices.Device
	(*ClockInfo)(nil),                 // 6: rblnservices.ClockInfo
	(*VersionInfo)(nil),               // 7: rblnservices.VersionInfo
	(*HWInfo)(nil),                    // 8: rblnservices.HWInfo
	(*MemoryInfo)(nil),                // 9: rblnservices.MemoryInfo
	(*UtilInfo)(nil),                  // 10: rblnservices.UtilInfo
	(*EventInfo)(nil),                 // 11: rblnservices.EventInfo
	(*DeviceInfo)(nil),                // 12: rblnservices.DeviceInfo
	(*Empty)(nil),                     // 13: rblnservices.Empty
	(*ErrorDetail)(nil),               // 14: rblnservices.ErrorDetail
	(*DeviceFilter)(nil),              // 15: rblnservices.DeviceFilter
	(*TopologyEntry)(nil),             // 16: rblnservices.TopologyEntry
	(*RblnListTopologyResponse)(nil),  // 17: rblnservices.RblnListTopologyResponse
	(*CoredumpEntry)(nil),             // 18: rblnservices.CoredumpEntry
	(*RblnListCoredumpsResponse)(nil), // 19: rblnservices.RblnListCoredumpsResponse
	(*RblnGetConfigRequest)(nil),      // 20: rblnservices.RblnGetConfigRequest
	(*RblnGetConfigResponse)(nil),     // 21: rblnservices.RblnGetConfigResponse
	(*RblnSetConfigRequest)(nil),      // 22: rblnservices.RblnSetConfigRequest
	(*RblnSetConfigResponse)(nil),     // 23: rblnservices.RblnSetConfigResponse
	(*GroupEntry)(nil),                // 24: rblnservices.GroupEntry
	(*RblnListGroupsResponse)(nil),    // 25: rblnservices.RblnListGroupsResponse
	(*RblnCreateGroupRequest)(nil),    // 26: rblnservices.RblnCreateGroupRequest
	(*RblnDestroyGroupRequest)(nil),   // 27: rblnservices.RblnDestroyGroupRequest
	(*RblnGroupOpResponse)(nil),       // 28: rblnservices.RblnGroupOpResponse
}
var file_rbln_services_proto_depIdxs = []int32{
	0,  // 0: rblnservices.StatusMsg.err_status:type_name -> rblnservices.Status
	0,  // 1: rblnservices.ClockInfo.err_status:type_name -> rblnservices.Status
	0,  // 2: rblnservices.VersionInfo.err_status:type_name -> rblnservices.Status
	0,  // 3: rblnservices.HWInfo.err_status:type_name -> rblnservices.Status
	0,  // 4: rblnservices.MemoryInfo.err_status:type_name -> rblnservices.Status
	0,  // 5: rblnservices.UtilInfo.err_status:type_name -> rblnservices.Status
	0,  // 6: rblnservices.DeviceInfo.err_status:type_name -> rblnservices.Status
	1,  // 7: rblnservices.DeviceInfo.dev_status:type_name -> rblnservices.DeviceStatus
	14, // 8: rblnservices.TopologyEntry.error:type_name -> rblnservices.ErrorDetail
	16, // 9: rblnservices.RblnListTopologyResponse.entries:type_name -> rblnservices.TopologyEntry
	14, // 10: rblnservices.CoredumpEntry.error:type_name -> rblnservices.ErrorDetail
	18, // 11: rblnservices.RblnListCoredumpsResponse.entries:type_name -> rblnservices.CoredumpEntry
	14, // 12: rblnservices.RblnGetConfigResponse.error:type_name -> rblnservices.ErrorDetail
	14, // 13: rblnservices.RblnSetConfigResponse.error:type_name -> rblnservices.ErrorDetail
	14, // 14: rblnservices.GroupEntry.error:type_name -> rblnservices.ErrorDetail
	24, // 15: rblnservices.RblnListGroupsResponse.entries:type_name -> rblnservices.GroupEntry
	14, // 16: rblnservices.RblnGroupOpResponse.error:type_name -> rblnservices.ErrorDetail
	13, // 17: rblnservices.RBLNServices.getDeviceList:input_type -> rblnservices.Empty
	13, // 18: rblnservices.RBLNServices.getServiceableDeviceList:input_type -> rblnservices.Empty
	5,  // 19: rblnservices.RBLNServices.resetDevice:input_type -> rblnservices.Device
	13, // 20: rblnservices.RBLNServices.resetAllDevice:input_type -> rblnservices.Empty
	5,  // 21: rblnservices.RBLNServices.getVersion:input_type -> rblnservices.Device
	5,  // 22: rblnservices.RBLNServices.getHWInfo:input_type -> rblnservices.Device
	5,  // 23: rblnservices.RBLNServices.getMemoryInfo:input_type -> rblnservices.Device
	5,  // 24: rblnservices.RBLNServices.getClockInfo:input_type -> rblnservices.Device
	5,  // 25: rblnservices.RBLNServices.getEventInfo:input_type -> rblnservices.Device
	13, // 26: rblnservices.RBLNServices.getTotalInfo:input_type -> rblnservices.Empty
	5,  // 27: rblnservices.RBLNServices.getUtilization:input_type -> rblnservices.Device
	15, // 28: rblnservices.RBLNServices.RblnListTopology:input_type -> rblnservices.DeviceFilter
	15, // 29: rblnservices.RBLNServices.RblnListCoredumps:input_type -> rblnservices.DeviceFilter
	20, // 30: rblnservices.RBLNServices.RblnGetConfig:input_type -> rblnservices.RblnGetConfigRequest
	22, // 31: rblnservices.RBLNServices.RblnSetConfig:input_type -> rblnservices.RblnSetConfigRequest
	13, // 32: rblnservices.RBLNServices.RblnListGroups:input_type -> rblnservices.Empty
	26, // 33: rblnservices.RBLNServices.RblnCreateGroup:input_type -> rblnservices.RblnCreateGroupRequest
	27, // 34: rblnservices.RBLNServices.RblnDestroyGroup:input_type -> rblnservices.RblnDestroyGroupRequest
	5,  // 35: rblnservices.RBLNServices.getDeviceList:output_type -> rblnservices.Device
	5,  // 36: rblnservices.RBLNServices.getServiceableDeviceList:output_type -> rblnservices.Device
	4,  // 37: rblnservices.RBLNServices.resetDevice:output_type -> rblnservices.StatusMsg
	4,  // 38: rblnservices.RBLNServices.resetAllDevice:output_type -> rblnservices.StatusMsg
	7,  // 39: rblnservices.RBLNServices.getVersion:output_type -> rblnservices.VersionInfo
	8,  // 40: rblnservices.RBLNServices.getHWInfo:output_type -> rblnservices.HWInfo
	9,  // 41: rblnservices.RBLNServices.getMemoryInfo:output_type -> rblnservices.MemoryInfo
	6,  // 42: rblnservices.RBLNServices.getClockInfo:output_type -> rblnservices.ClockInfo
	11, // 43: rblnservices.RBLNServices.getEventInfo:output_type -> rblnservices.EventInfo
	12, // 44: rblnservices.RBLNServices.getTotalInfo:output_type -> rblnservices.DeviceInfo
	10, // 45: rblnservices.RBLNServices.getUtilization:output_type -> rblnservices.UtilInfo
	17, // 46: rblnservices.RBLNServices.RblnListTopology:output_type -> rblnservices.RblnListTopologyResponse
	19, // 47: rblnservices.RBLNServices.RblnListCoredumps:output_type -> rblnservices.RblnListCoredumpsResponse
	21, // 48: rblnservices.RBLNServices.RblnGetConfig:output_type -> rblnservices.RblnGetConfigResponse
	23, // 49: rblnservices.RBLNServices.RblnSetConfig:output_type -> rblnservices.RblnSetConfigResponse
	25, // 50: rblnservices.RBLNServices.RblnListGroups:output_type -> rblnservices.RblnListGroupsResponse
	28, // 51: rblnservices.RBLNServices.RblnCreateGroup:output_type -> rblnservices.RblnGroupOpResponse
	28, // 52: rblnservices.RBLNServices.RblnDestroyGroup:output_type -> rblnservices.RblnGroupOpResponse
	35, // [35:53] is the sub-list for method output_type
	17, // [17:35] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_rbln_services_proto_init() }
func file_rbln_services_proto_init() {
	if File_rbln_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rbln_services_proto_rawDesc), len(file_rbln_services_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rbln_services_proto_goTypes,
		DependencyIndexes: file_rbln_services_proto_depIdxs,
		EnumInfos:         file_rbln_services_proto_enumTypes,
		MessageInfos:      file_rbln_services_proto_msgTypes,
	}.Build()
	File_rbln_services_proto = out.File
	file_rbln_services_proto_goTypes = nil
	file_rbln_services_proto_depIdxs = nil
}
